# Generated by Django 2.1.4 on 2019-01-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devid', models.CharField(db_index=True, max_length=256, unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataloggerForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='', help_text='All required configuration parameters in JSON format')),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=256)),
                ('handler', models.CharField(choices=[('internalplugin.ColumnDataEndpoint', 'internalplugin.ColumnDataEndpoint'), ('internalplugin.DummyEndpoint', 'internalplugin.DummyEndpoint'), ('internalplugin.KeyVal', 'internalplugin.KeyVal'), ('thirdparty.SomePlugin', 'thirdparty.SomePlugin')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(choices=[('internalplugin.FileDumpForward', 'internalplugin.FileDumpForward'), ('thirdparty.DummyHttpForward', 'thirdparty.DummyHttpForward')], max_length=64)),
                ('config', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dataloggerforward',
            name='dataforward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesslogic.Forward'),
        ),
        migrations.AddField(
            model_name='dataloggerforward',
            name='datalogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesslogic.Datalogger'),
        ),
        migrations.AddField(
            model_name='datalogger',
            name='forwards',
            field=models.ManyToManyField(blank=True, through='businesslogic.DataloggerForward', to='businesslogic.Forward', verbose_name='Data to forward'),
        ),
    ]
