# Generated by Django 2.2b1 on 2019-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='', help_text='All required configuration parameters in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler', models.CharField(choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder')], max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='', help_text='All required configuration parameters in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(db_index=True, max_length=256)),
                ('handler', models.CharField(choices=[('demoplugin.ColumnDataEndpoint', 'demoplugin.ColumnDataEndpoint'), ('demoplugin.DummyEndpoint', 'demoplugin.DummyEndpoint'), ('demoplugin.DumpRequestEndpoint', 'demoplugin.DumpRequestEndpoint'), ('demoplugin.KeyVal', 'demoplugin.KeyVal'), ('demoplugin.RabbitMQEndpoint', 'demoplugin.RabbitMQEndpoint'), ('thingpark.ThingparkEndpoint', 'thingpark.ThingparkEndpoint')], max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='', help_text='All required configuration parameters in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler', models.CharField(choices=[('demoplugin.DummyHttpForward', 'demoplugin.DummyHttpForward'), ('demoplugin.FileDumpForward', 'demoplugin.FileDumpForward'), ('thingpark.AQBurk2NGSIForward', 'thingpark.AQBurk2NGSIForward'), ('thingpark.DummyHttpForward', 'thingpark.DummyHttpForward'), ('thingpark.FileDumpForward', 'thingpark.FileDumpForward')], max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
