# Generated by Django 2.2b1 on 2019-02-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devid', models.CharField(db_index=True, max_length=256, unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(choices=[('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder')], max_length=64)),
                ('config', models.TextField(default='', help_text='All required configuration parameters in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=256)),
                ('handler', models.CharField(choices=[('demoplugin.ColumnDataEndpoint', 'demoplugin.ColumnDataEndpoint'), ('demoplugin.DummyEndpoint', 'demoplugin.DummyEndpoint'), ('demoplugin.DumpRequestEndpoint', 'demoplugin.DumpRequestEndpoint'), ('demoplugin.KeyVal', 'demoplugin.KeyVal'), ('demoplugin.RabbitMQEndpoint', 'demoplugin.RabbitMQEndpoint'), ('thingpark.ThingparkEndpoint', 'thingpark.ThingparkEndpoint')], max_length=64)),
                ('config', models.TextField(default='', help_text='All required configuration parameters in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(choices=[('demoplugin.DummyHttpForward', 'demoplugin.DummyHttpForward'), ('demoplugin.FileDumpForward', 'demoplugin.FileDumpForward'), ('thingpark.DummyHttpForward', 'thingpark.DummyHttpForward'), ('thingpark.FileDumpForward', 'thingpark.FileDumpForward')], max_length=64)),
                ('config', models.TextField(default='', help_text='All required configuration parameters in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataloggerForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='', help_text='All required configuration parameters in JSON format')),
                ('dataforward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Forward')),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Datalogger')),
            ],
        ),
        migrations.AddField(
            model_name='datalogger',
            name='forwards',
            field=models.ManyToManyField(blank=True, through='broker.DataloggerForward', to='broker.Forward', verbose_name='Data to forward'),
        ),
    ]
