# Generated by Django 2.2b1 on 2019-03-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devid', models.CharField(db_index=True, max_length=256, unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('decoder', models.CharField(blank=True, choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder')], max_length=128)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('locality', models.CharField(blank=True, max_length=256)),
                ('street', models.CharField(blank=True, max_length=256)),
                ('activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='decoder',
            name='handler',
            field=models.CharField(choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder')], max_length=64),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='handler',
            field=models.CharField(choices=[('demoplugin.ColumnDataEndpoint', 'demoplugin.ColumnDataEndpoint'), ('demoplugin.DummyEndpoint', 'demoplugin.DummyEndpoint'), ('demoplugin.DumpRequestEndpoint', 'demoplugin.DumpRequestEndpoint'), ('demoplugin.KeyVal', 'demoplugin.KeyVal'), ('demoplugin.RabbitMQEndpoint', 'demoplugin.RabbitMQEndpoint'), ('thingpark.ThingparkEndpoint', 'thingpark.ThingparkEndpoint'), ('everynet.ThingparkEndpoint', 'everynet.ThingparkEndpoint'), ('experiments.EspEasyPostEndpoint', 'experiments.EspEasyPostEndpoint')], max_length=64),
        ),
        migrations.AlterField(
            model_name='forward',
            name='handler',
            field=models.CharField(choices=[('demoplugin.DummyHttpForward', 'demoplugin.DummyHttpForward'), ('demoplugin.FileDumpForward', 'demoplugin.FileDumpForward'), ('thingpark.AQBurk2NGSIForward', 'thingpark.AQBurk2NGSIForward'), ('thingpark.DummyHttpForward', 'thingpark.DummyHttpForward'), ('thingpark.FileDumpForward', 'thingpark.FileDumpForward'), ('experiments.AQBurk2NGSIForward', 'experiments.AQBurk2NGSIForward'), ('experiments.DummyHttpForward', 'experiments.DummyHttpForward'), ('experiments.FileDumpForward', 'experiments.FileDumpForward')], max_length=64),
        ),
        migrations.CreateModel(
            name='DataloggerForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='{}', help_text='All required configuration parameters in JSON format')),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Datalogger')),
                ('forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_forwards', to='broker.Forward')),
            ],
        ),
        migrations.AddField(
            model_name='datalogger',
            name='forwards',
            field=models.ManyToManyField(blank=True, related_name='related_dataloggers', through='broker.DataloggerForward', to='broker.Forward', verbose_name='Data to forward'),
        ),
    ]
