# Generated by Django 2.2rc1 on 2019-04-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_add_datalogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoder',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='decoder',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='forward',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='forward',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataloggerforward',
            name='datalogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataloggerforwards', to='broker.Datalogger'),
        ),
        migrations.AlterField(
            model_name='dataloggerforward',
            name='forward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataloggerforwards', to='broker.Forward'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='handler',
            field=models.CharField(choices=[('demoplugin.ColumnDataEndpoint', 'demoplugin.ColumnDataEndpoint'), ('demoplugin.DummyEndpoint', 'demoplugin.DummyEndpoint'), ('demoplugin.DumpRequestEndpoint', 'demoplugin.DumpRequestEndpoint'), ('demoplugin.KeyVal', 'demoplugin.KeyVal'), ('demoplugin.RabbitMQEndpoint', 'demoplugin.RabbitMQEndpoint'), ('thingpark.ThingparkEndpoint', 'thingpark.ThingparkEndpoint'), ('everynet.EverynetEndpoint', 'everynet.EverynetEndpoint'), ('experiments.RfidEndpoint', 'experiments.RfidEndpoint')], max_length=64),
        ),
        migrations.AlterField(
            model_name='forward',
            name='handler',
            field=models.CharField(choices=[('broker.InfluxDBForward', 'broker.InfluxDBForward'), ('demoplugin.DummyHttpForward', 'demoplugin.DummyHttpForward'), ('demoplugin.FileDumpForward', 'demoplugin.FileDumpForward'), ('thingpark.AQBurk2NGSIForward', 'thingpark.AQBurk2NGSIForward'), ('thingpark.DummyHttpForward', 'thingpark.DummyHttpForward'), ('thingpark.FileDumpForward', 'thingpark.FileDumpForward'), ('thingpark.Paxcounter2NGSIForward', 'thingpark.Paxcounter2NGSIForward')], max_length=64),
        ),
    ]
