# Generated by Django 2.2 on 2019-04-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_auto_20190411_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalogger',
            name='decoder',
            field=models.CharField(blank=True, choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.ElsysDecoder', 'thingpark.ElsysDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder'), ('ehp.DL12Decoder', 'ehp.DL12Decoder'), ('ehp.DL6Decoder', 'ehp.DL6Decoder'), ('owntracks.AQBurkDecoder', 'owntracks.AQBurkDecoder')], max_length=128),
        ),
        migrations.AlterField(
            model_name='decoder',
            name='handler',
            field=models.CharField(choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.ElsysDecoder', 'thingpark.ElsysDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder'), ('ehp.DL12Decoder', 'ehp.DL12Decoder'), ('ehp.DL6Decoder', 'ehp.DL6Decoder'), ('owntracks.AQBurkDecoder', 'owntracks.AQBurkDecoder')], max_length=64),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='handler',
            field=models.CharField(choices=[('demoplugin.ColumnDataEndpoint', 'demoplugin.ColumnDataEndpoint'), ('demoplugin.DummyEndpoint', 'demoplugin.DummyEndpoint'), ('demoplugin.DumpRequestEndpoint', 'demoplugin.DumpRequestEndpoint'), ('demoplugin.KeyVal', 'demoplugin.KeyVal'), ('demoplugin.RabbitMQEndpoint', 'demoplugin.RabbitMQEndpoint'), ('thingpark.ThingparkEndpoint', 'thingpark.ThingparkEndpoint'), ('everynet.EverynetEndpoint', 'everynet.EverynetEndpoint'), ('experiments.RfidEndpoint', 'experiments.RfidEndpoint'), ('ehp.EhpDL6Endpoint', 'ehp.EhpDL6Endpoint'), ('ehp.EhpDL12Endpoint', 'ehp.EhpDL12Endpoint'), ('owntracks.OwnTracksEndpoint', 'owntracks.OwnTracksEndpoint')], max_length=64),
        ),
    ]
