# Generated by Django 2.2 on 2019-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_auto_20190423_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='handler',
            field=models.CharField(choices=[('thingpark.ThingparkEndpoint', 'thingpark.ThingparkEndpoint'), ('everynet.EverynetEndpoint', 'everynet.EverynetEndpoint'), ('experiments.RfidEndpoint', 'experiments.RfidEndpoint'), ('ehp.EhpDL6Endpoint', 'ehp.EhpDL6Endpoint'), ('ehp.EhpDL12Endpoint', 'ehp.EhpDL12Endpoint'), ('owntracks.OwnTracksEndpoint', 'owntracks.OwnTracksEndpoint')], max_length=64),
        ),
        migrations.AlterField(
            model_name='forward',
            name='handler',
            field=models.CharField(choices=[('broker.InfluxDBForward', 'broker.InfluxDBForward'), ('thingpark.AQBurk2NGSIForward', 'thingpark.AQBurk2NGSIForward'), ('thingpark.DummyHttpForward', 'thingpark.DummyHttpForward'), ('thingpark.FileDumpForward', 'thingpark.FileDumpForward'), ('thingpark.Paxcounter2NGSIForward', 'thingpark.Paxcounter2NGSIForward')], max_length=64),
        ),
    ]
