# Generated by Django 2.2 on 2019-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_auto_20190423_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalogger',
            name='decoder',
            field=models.CharField(blank=True, choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.ElsysDecoder', 'thingpark.ElsysDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder'), ('ehp.DL12Decoder', 'ehp.DL12Decoder'), ('ehp.DL6Decoder', 'ehp.DL6Decoder'), ('gpslocation.AQBurkDecoder', 'gpslocation.AQBurkDecoder')], max_length=128),
        ),
        migrations.AlterField(
            model_name='decoder',
            name='handler',
            field=models.CharField(choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.ElsysDecoder', 'thingpark.ElsysDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder'), ('ehp.DL12Decoder', 'ehp.DL12Decoder'), ('ehp.DL6Decoder', 'ehp.DL6Decoder'), ('gpslocation.AQBurkDecoder', 'gpslocation.AQBurkDecoder')], max_length=64),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='handler',
            field=models.CharField(choices=[('thingpark.ThingparkEndpoint', 'thingpark.ThingparkEndpoint'), ('everynet.EverynetEndpoint', 'everynet.EverynetEndpoint'), ('experiments.RfidEndpoint', 'experiments.RfidEndpoint'), ('ehp.EhpDL6Endpoint', 'ehp.EhpDL6Endpoint'), ('ehp.EhpDL12Endpoint', 'ehp.EhpDL12Endpoint'), ('gpslocation.MapMyTracksEndpoint', 'gpslocation.MapMyTracksEndpoint'), ('gpslocation.OwnTracksEndpoint', 'gpslocation.OwnTracksEndpoint')], max_length=64),
        ),
    ]
