# Generated by Django 2.2.1 on 2019-05-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_auto_20190427_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('config', models.TextField(default='', help_text='All required configuration parameters in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decoder', models.CharField(blank=True, choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.ElsysDecoder', 'thingpark.ElsysDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder')], max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='decoder',
            field=models.CharField(blank=True, choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.ElsysDecoder', 'thingpark.ElsysDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder')], max_length=128),
        ),
        migrations.AlterField(
            model_name='decoder',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='decoder',
            name='handler',
            field=models.CharField(choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.ElsysDecoder', 'thingpark.ElsysDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder')], max_length=64),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='handler',
            field=models.CharField(choices=[('thingpark.ThingparkEndpoint', 'thingpark.ThingparkEndpoint'), ('thethings.TheThingsEndpoint', 'thethings.TheThingsEndpoint'), ('everynet.EverynetEndpoint', 'everynet.EverynetEndpoint')], max_length=64),
        ),
        migrations.AlterField(
            model_name='forward',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='datalogger',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataloggers', to='broker.Application'),
        ),
    ]
